mod agent;
mod diff;
mod file_tree;
mod git;
mod github;
mod logs;
mod mouse;
mod mouse_clicks;
mod notifications;
mod palette;
mod preview;
mod render;
mod scrollback;
mod search;
mod shell;
mod status_bar;
mod tabs;

pub use file_tree::{file_tree_interaction_at, FileTreeMouseAction};
pub use git::{git_interaction_at, git_viewport_rows};
pub use github::{github_issue_interaction_at, issue_detail_viewport_rows, issues_viewport_rows};
pub use mouse::map_mouse_click;
pub use mouse::mouse_interactions_enabled;
pub use mouse_clicks::{DoubleClickTarget, DoubleClickTracker};
pub use palette::palette_match_at;
pub use render::draw_frame;
pub use search::search_interaction_at;
