mod agent;
mod file_tree;
mod logs;
mod mouse;
mod notifications;
mod palette;
mod preview;
mod render;
mod scrollback;
mod search;
mod shell;
mod status_bar;
mod tabs;

pub use file_tree::{file_tree_interaction_at, FileTreeMouseAction};
pub use mouse::map_mouse_click;
pub use mouse::mouse_interactions_enabled;
pub use palette::palette_match_at;
pub use render::draw_frame;
pub use search::search_interaction_at;
