[patch."https://github.com/pacificnm/nest"]
nest-ai = { path = "../../../core/crates/nest-ai" }
nest-ai-ollama = { path = "../../../modules/crates/nest-ai-ollama" }
nest-agent = { path = "../../../core/crates/nest-agent" }
nest-cli = { path = "../../../core/crates/nest-cli" }
nest-config = { path = "../../../core/crates/nest-config" }
nest-core = { path = "../../../core/crates/nest-core" }
nest-error = { path = "../../../core/crates/nest-error" }
nest-file = { path = "../../../core/crates/nest-file" }
nest-http = { path = "../../../core/crates/nest-http" }
nest-http-client = { path = "../../../core/crates/nest-http-client" }
nest-logging = { path = "../../../core/crates/nest-logging" }
nest-mcp = { path = "../../../core/crates/nest-mcp" }
