#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KNOWLEDGE="${KIWI_KNOWLEDGE:-${HOME}/kiwi-knowledge}"
PYTHON="${ROOT}/.venv/bin/python"
BINARY="${KIWI_MCP_MEMORY:-${ROOT}/target/release/kiwi-mcp-memory}"

if [[ ! -x "$BINARY" ]]; then
  BINARY="${ROOT}/target/debug/kiwi-mcp-memory"
fi
if [[ ! -x "$BINARY" ]]; then
  BINARY="kiwi-mcp-memory"
fi

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT}/.env"
  set +a
fi

if [[ ! -d "$KNOWLEDGE" ]]; then
  echo "ERROR: knowledge directory not found: ${KNOWLEDGE}" >&2
  echo "Clone or download books into ~/kiwi-knowledge, or set KIWI_KNOWLEDGE." >&2
  exit 1
fi

CFG="$(mktemp)"
trap 'rm -f "$CFG"' EXIT

cat >"$CFG" <<EOF
# Generated by scripts/index-knowledge.sh — reference manuals for kiwi-mcp-memory

[[collections]]
name = "rust-book"
source = "${KNOWLEDGE}/rust/rust-book/src"
extensions = ["md"]

[[collections]]
name = "rust-by-example"
source = "${KNOWLEDGE}/rust/rust-by-example/src"
extensions = ["md"]

[[collections]]
name = "rust-reference"
source = "${KNOWLEDGE}/rust/rust-reference/src"
extensions = ["md"]

[[collections]]
name = "egui"
source = "${KNOWLEDGE}/egui/crates/egui/src"
extensions = ["rs", "md"]

[[collections]]
name = "eframe"
source = "${KNOWLEDGE}/egui/crates/eframe/src"
extensions = ["rs", "md"]

[[collections]]
name = "egui-docs"
source = "${KNOWLEDGE}/egui/docs"
extensions = ["md"]
EOF

echo "Knowledge root: ${KNOWLEDGE}"
echo "Ensuring knowledge_base schema…"
if [[ -x "$PYTHON" ]]; then
  if ! "$PYTHON" "${ROOT}/tools/setup_knowledge_base.py"; then
    echo "Trying postgres one-time setup (may prompt for sudo)…" >&2
    if sudo -u postgres psql kiwi_memory <"${ROOT}/tools/setup_knowledge_base.sql"; then
      echo "knowledge_base created via postgres."
    else
      echo "ERROR: knowledge_base table is missing and could not be created." >&2
      echo "Run manually:" >&2
      echo "  sudo -u postgres psql kiwi_memory < ${ROOT}/tools/setup_knowledge_base.sql" >&2
      exit 1
    fi
  fi
else
  "$BINARY" --setup-db || {
    echo "ERROR: run postgres setup:" >&2
    echo "  sudo -u postgres psql kiwi_memory -f ${ROOT}/tools/setup_knowledge_base.sql" >&2
    exit 1
  }
fi

echo "Indexing knowledge collections (OpenAI embeddings; may take several minutes)…"
"$BINARY" --index-kb --kb-config "$CFG"

echo "Indexed collections:"
"$BINARY" --list-collections
