[agent]
agent_mode = true
allow_save_context = false
disabled_mcp_servers = []
max_steps = 10
mcp_config = "../../../.cursor/mcp.json"
mcp_servers = [
    "nest-memory",
    "nest-knowledge",
    "nest-context-memory",
]
model = "qwen2.5:3b"

[ai]
base_url = "http://192.168.88.10:11434"
enabled = true
host = "192.168.88.10"
model = "qwen2.5:3b"
models = [
    "nomic-embed-text:latest",
    "llama3.2:3b",
    "qwen2.5-coder:3b",
    "qwen2.5-coder:7b",
    "qwen2.5:7b",
    "qwen2.5:3b",
]
port = 11434
provider = "ollama"

[gui]
height = 900
title = "Kiwi"
vsync = true
width = 1600

[project]
name = "nest"
root = "../../.."
